services:
  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - postgresDB:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: unless-stopped

  ahorcado:
    image: ahorcado:latest
    build: .
    ports:
      - "5000:5000" 
    working_dir: /ahorcado
    volumes:
      - ./:/ahorcado
    env_file: .env
    depends_on:
      - postgres
    command: >
      sh -c "pip install --upgrade pip && pip install --no-cache-dir --root-user-action=ignore -r requirements.txt && python ahorcado.py"
volumes:
  postgresDB: